name: Tiles
description: Generate tiles

runs:
  using: "composite"
  steps:
    - name: Tiles & data from cache
      id: tile-cache
      uses: actions/cache@v4
      with:
        path: |
          tile-server/tiles/*
          data/generated/*
        key: tiles-${{ env.DATE }}-${{ hashFiles('data/**', 'tile-server/generate-tiles.sh') }}

    - name: Generate tiles & data
      if: ${{ steps.tile-cache.outputs.cache-hit != 'true' }}
      shell: "bash"
      run: yarn generate:tiles
