name: Tiles and data
description: Generate tiles and data

runs:
  using: "composite"
  steps:
    - name: Tiles & data from cache
      id: tile-cache
      uses: actions/cache@v4
      with:
        path: |
          public/tiles/*
          generated/*
        key: tiles-${{ env.DATE }}-${{ hashFiles('prebuild/**') }}

    - name: Generate tiles & data
      if: ${{ steps.tile-cache.outputs.cache-hit != 'true' }}
      shell: "bash"
      run: yarn generate:all
