name: Tippecanoe
description: Install Tippecanoe

runs:
  using: "composite"
  steps:
    - name: Tippecanoe from cache
      id: tippecanoe-cache
      uses: actions/cache@v4
      with:
        path: tippecanoe
        key: tippecanoe-${{ env.TIPPECANOE_VERSION }}

    - name: Install tippecanoe
      if: steps.tippecanoe-cache.outputs.cache-hit != 'true'
      run: yarn ci:install-tippecanoe
      shell: "bash"
