import "./globals.css";

import type { Metadata } from "next";
import { MapboxMap } from "@/components/mapbox/map";
import { MapboxMapProvider } from "@/components/mapbox/context";
import { NavBar } from "@/components/navbar";
import { SideBar } from "@/components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter">
      <head>
        <link
          rel="stylesheet"
          href="https://js.arcgis.com/4.29/esri/themes/light/main.css"
        ></link>
      </head>
      <body className="h-screen w-screen relative bg-base-200 flex flex-col gap-2">
        <MapboxMapProvider>
          <NavBar />
          <div className="z-10 relative flex-1 m-8">
            <SideBar />
            {children}
          </div>
          <MapboxMap />
        </MapboxMapProvider>
      </body>
    </html>
  );
}
