name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
permissions:
  checks: write
  contents: read
  pull-requests: write
  deployments: write
jobs:
  build_and_deploy:
    name: Production deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set Env Vars
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tippecanoe
        uses: ./.github/actions/tippecanoe
        env:
          TIPPECANOE_VERSION: ${{ secrets.TIPPECANOE_VERSION }}

      - name: Install Node Dependencies
        uses: ./.github/actions/node

      - name: Data
        uses: ./.github/actions/data
        env:
          DATE: ${{ env.DATE }}

      - name: Tiles
        uses: ./.github/actions/tiles
        env:
          DATE: ${{ env.DATE }}

      - name: Firebase Deploy Tiles (Production)
        id: firebase-tiles
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          channelId: live
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LC_TILES }}"
          entryPoint: ./tile-server
          projectId: lc-tiles

      - name: Deploy to Vercel (Production)
        uses: BetaHuhn/deploy-to-vercel-action@v1
        id: vercel-deploy
        with:
          CREATE_COMMENT: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          BUILD_ENV: |
            NEXT_PUBLIC_MAPBOX_TOKEN=${{ secrets.MAPBOX_API_KEY }}
            NEXT_PUBLIC_TILE_SERVER_DOMAIN=https://lc-tiles.web.app
